### ISSUE TITLE
App is no longer working (wrong worker class)

### ISSUE THREAD

**Issue by deathtracktor** [sseg/heroku-aiohttp-template#1]
App template is no longer working in the current Heroku environment.
According to [aiohttp documentation](http://aiohttp.readthedocs.io/en/v0.18.4/gunicorn.html), the `Procfile` should be changed in order to use a dedicated worker class:
```
web: gunicorn web:main --worker-class aiohttp.worker.GunicornWebWorker --config config/gunicorn.conf
```
The default worker generates a weird error message:
```
aiohttp TypeError: __call__() takes 1 positional argument but 3 were given
```

**Comment by sseg** [comment]
Thanks for the note!
The gunicorn worker is already specified here: https://github.com/sseg/heroku-aiohttp-web/blob/045da82faed2c0b48cfb5fc4283c33b375e9ba20/config/gunicorn.conf#L5

I wasn't able to reproduce this (or any other errors) using either of the two heroku deployment strategies (deploy button or CLI) or when using the app locally with Python 3.5.2.

Can you include some more details about the environment you're using? Specifically:
```sh
$ python --version
$ pip freeze
```

**Comment by deathtracktor** [comment]
Hi,
surprisingly, I have not been able to reproduce it either (just deployed it again from scratch) :)
I will keep monitoring this one.
Thanks for your response!
